import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>iFood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to iFood
        </h1>

        <p className={styles.description}>
          Why pick your food when you can iFood your meal{' '}.
          Page: <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="api/hello" className={styles.card}>
            <h2>Hello World &rarr;</h2>
            <p>Make sure that NEXT.js runs without any problems</p>
          </a>

          <a href="api/recipe" className={styles.card}>
            <h2>Recipe &rarr;</h2>
            <p>Make sure that Prisma is connected to PostgreSQL.</p>
          </a>

          <a
            href="https://github.com/incubation-center/FullStack-Website---Group6"
            className={styles.card}
          >
            <h2>Github &rarr;</h2>
            <p>FullStack-Website---Group6.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Comming Soon &rarr;</h2>
            <p>
              Currently in development
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} Group 6
        </a>
      </footer>
    </div>
  )
}

export default Home
